development:
  clients:
    default:
      database: <%= File.basename(PADRINO_ROOT) %>
      hosts:
        - localhost:27017
        
test:
  clients:
    default:
      database: <%= File.basename(PADRINO_ROOT) %>_test
      hosts:
        - localhost:27017   

production:
  clients:
    default:
      uri: <%= ENV['MONGODB_URI'] || ENV['MONGO_URL'] %>